methodologies_short_names = ['product backlog',
                'sprint backlog',
                'sprint burndown chart',
                'estimation',
                'sprint planning',
                'daily stand up meeting',
                'sprint review',
                'sprint retrospective',
                'kanban',
                'user stories',
                'small releases',
                'refactoring',
                'automated tests',
                'pair programming',
                'CI',
                'coding standards',
                ]